[build-system]
requires = ["setuptools>=63.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "auto_flow_pipeline"
version = "0.1.0"
description = "This is the pipeline to use AutoFlow..."
dependencies = []

[tool.setuptools.packages.find]
where = ["src"]